import type { Payslip, AnomalyResult, PayTrend } from './types';

/** Sample payslips for demo mode so prospective users can explore the product. */
export const DEMO_PAYSLIPS: Payslip[] = [
  {
    id: 'demo-1',
    employer_name: 'Acme Corp',
    file_name: 'payslip-jan-2026.pdf',
    pay_date: '2026-01-31',
    pay_period_start: '2026-01-01',
    pay_period_end: '2026-01-31',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2847.50,
    tax_amount: 510,
    ni_amount: 312.50,
    pension_amount: 80,
    total_deductions: 902.50,
    taxable_pay: 3750,
    review_checks_status: 'complete',
    review_checks_revision: 1,
    anomaly_count: 0,
  },
  {
    id: 'demo-2',
    employer_name: 'Acme Corp',
    file_name: 'payslip-feb-2026.pdf',
    pay_date: '2026-02-28',
    pay_period_start: '2026-02-01',
    pay_period_end: '2026-02-28',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2847.50,
    tax_amount: 510,
    ni_amount: 312.50,
    pension_amount: 80,
    total_deductions: 902.50,
    taxable_pay: 3750,
    review_checks_status: 'complete',
    review_checks_revision: 1,
    anomaly_count: 0,
  },
  {
    id: 'demo-3',
    employer_name: 'Acme Corp',
    file_name: 'payslip-mar-2026.pdf',
    pay_date: '2026-03-31',
    pay_period_start: '2026-03-01',
    pay_period_end: '2026-03-31',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2710.00,
    tax_amount: 640,
    ni_amount: 312.50,
    pension_amount: 87.50,
    total_deductions: 1040,
    taxable_pay: 3750,
    currency: 'GBP',
    extraction_confidence: 'high',
    extraction_context: {
      tax_code: '1257L',
      national_insurance_category: 'A',
      prsi_class: null,
      pay_frequency: 'monthly',
      pay_basis: 'Salary',
    },
    extraction_context_reviewed: true,
    extraction_line_items: [
      {
        label: 'Basic pay',
        kind: 'earning',
        amount: 3750,
        year_to_date_amount: 11250,
        evidence: 'Basic pay £3,750.00',
        confidence: 'high',
        reviewed: true,
      },
      {
        label: 'PAYE tax',
        kind: 'deduction',
        amount: 640,
        year_to_date_amount: 1660,
        evidence: 'PAYE tax £640.00',
        confidence: 'high',
        reviewed: true,
      },
      {
        label: 'National Insurance',
        kind: 'deduction',
        amount: 312.50,
        year_to_date_amount: 937.50,
        evidence: 'National Insurance £312.50',
        confidence: 'high',
        reviewed: true,
      },
      {
        label: 'Employee pension',
        kind: 'deduction',
        amount: 87.50,
        year_to_date_amount: 247.50,
        evidence: 'Employee pension £87.50',
        confidence: 'medium',
        reviewed: true,
      },
    ],
    extraction_field_evidence: [
      { field: 'gross_pay', evidence: 'Gross pay £3,750.00', confidence: 'high' },
      { field: 'net_pay', evidence: 'Net pay £2,710.00', confidence: 'high' },
    ],
    year_to_date: { gross_pay: 11250, tax: 1660, ni: 937.50, pension: 247.50 },
    year_to_date_reviewed: true,
    review_checks_status: 'complete',
    review_checks_revision: 1,
    anomaly_count: 2,
  },
];

export const DEMO_ANOMALIES: AnomalyResult[] = [
  {
    id: 'demo-a1',
    payslip_id: 'demo-3',
    payslip_date: '2026-03-31',
    employer_name: 'Acme Corp',
    anomaly_type: 'tax_disproportionate',
    severity: 'high',
    confidence: 'high',
    title: 'Tax increased more than expected',
    description:
      'What changed: Your income tax moved from \u00a3510.00 to \u00a3640.00 \u2014 a \u00a3130.00 increase (25.5%) \u2014 while your gross pay stayed the same.\n\nWhy it matters: This can happen after a tax-code change or another valid payroll adjustment, but the reason should be clear in your records.',
    status: 'new',
    suggested_action:
      'Compare the tax code on this payslip with your HMRC personal tax account. If the reason for the change is not clear, ask payroll to explain the calculation.',
  },
  {
    id: 'demo-a2',
    payslip_id: 'demo-3',
    payslip_date: '2026-03-31',
    employer_name: 'Acme Corp',
    anomaly_type: 'same_gross_different_net',
    severity: 'medium',
    confidence: 'high',
    title: 'Same gross pay but different take-home',
    description:
      "What changed: Your gross pay is essentially the same, but your take-home pay dropped by \u00a3137.50. Something in your deductions changed.\n\nWhy it matters: When gross stays the same but net moves, a deduction was added or adjusted.",
    status: 'new',
    suggested_action:
      "Compare each deduction line against last month's payslip. Focus on tax and pension to identify what shifted.",
  },
];

export const DEMO_TRENDS: PayTrend[] = DEMO_PAYSLIPS.map((s) => ({
  month: new Date(s.pay_date).toLocaleDateString('en-GB', { month: 'short', year: '2-digit' }),
  gross: s.gross_pay,
  net: s.net_pay,
  tax: s.tax_amount,
  deductions: s.total_deductions,
}));
