import type { Payslip, AnomalyResult, IssueDraft, PayTrend } from './types';
export { formatDate } from './date-utils';

export const demoPayslips: Payslip[] = [
  {
    id: 'ps-001',
    employer_name: 'Acme Technologies Ltd',
    file_name: 'payslip-oct-2025.pdf',
    pay_date: '2025-10-31',
    pay_period_start: '2025-10-01',
    pay_period_end: '2025-10-31',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2737,
    tax_amount: 491,
    ni_amount: 372,
    pension_amount: 150,
    total_deductions: 1013,
    taxable_pay: 3600,
    anomaly_count: 0,
  },
  {
    id: 'ps-002',
    employer_name: 'Acme Technologies Ltd',
    file_name: 'payslip-nov-2025.pdf',
    pay_date: '2025-11-30',
    pay_period_start: '2025-11-01',
    pay_period_end: '2025-11-30',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2742,
    tax_amount: 486,
    ni_amount: 372,
    pension_amount: 150,
    total_deductions: 1008,
    taxable_pay: 3600,
    anomaly_count: 0,
  },
  {
    id: 'ps-003',
    employer_name: 'Acme Technologies Ltd',
    file_name: 'payslip-dec-2025.pdf',
    pay_date: '2025-12-31',
    pay_period_start: '2025-12-01',
    pay_period_end: '2025-12-31',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 5250,
    net_pay: 3612,
    tax_amount: 891,
    ni_amount: 522,
    pension_amount: 225,
    bonus_amount: 1500,
    total_deductions: 1638,
    taxable_pay: 5025,
    anomaly_count: 1,
  },
  {
    id: 'ps-004',
    employer_name: 'Acme Technologies Ltd',
    file_name: 'payslip-jan-2026.pdf',
    pay_date: '2026-01-31',
    pay_period_start: '2026-01-01',
    pay_period_end: '2026-01-31',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2680,
    tax_amount: 548,
    ni_amount: 372,
    pension_amount: 150,
    total_deductions: 1070,
    taxable_pay: 3600,
    anomaly_count: 1,
  },
  {
    id: 'ps-005',
    employer_name: 'Acme Technologies Ltd',
    file_name: 'payslip-feb-2026.pdf',
    pay_date: '2026-02-28',
    pay_period_start: '2026-02-01',
    pay_period_end: '2026-02-28',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2695,
    tax_amount: 491,
    ni_amount: 414,
    pension_amount: 150,
    total_deductions: 1055,
    taxable_pay: 3600,
    anomaly_count: 1,
  },
  {
    id: 'ps-006',
    employer_name: 'Acme Technologies Ltd',
    file_name: 'payslip-mar-2026.pdf',
    pay_date: '2026-03-31',
    pay_period_start: '2026-03-01',
    pay_period_end: '2026-03-31',
    country: 'UK',
    status: 'confirmed',
    gross_pay: 3750,
    net_pay: 2540,
    tax_amount: 491,
    ni_amount: 372,
    pension_amount: 150,
    student_loan_amount: 197,
    total_deductions: 1210,
    taxable_pay: 3600,
    anomaly_count: 2,
  },
];

export const demoAnomalies: AnomalyResult[] = [
  {
    id: 'an-001',
    payslip_id: 'ps-003',
    payslip_date: '2025-12-31',
    employer_name: 'Acme Technologies Ltd',
    anomaly_type: 'gross_pay_change',
    severity: 'medium',
    confidence: 'high',
    title: 'Gross pay increased noticeably',
    description: 'What changed: Your gross pay went from £3,750.00 to £5,250.00 — a £1,500.00 difference (40.0%). This payslip includes a bonus payment, which may explain the change.\n\nWhy it matters: An increase could reflect overtime, a bonus, a pay rise, or an error. It\'s worth confirming the reason.\n\nThis may be perfectly valid, but it\'s worth checking.',
    status: 'reviewed',
    suggested_action: 'Check if the bonus amount explains the full difference. If the change is unexpected, ask your payroll team to clarify.',
  },
  {
    id: 'an-002',
    payslip_id: 'ps-004',
    payslip_date: '2026-01-31',
    employer_name: 'Acme Technologies Ltd',
    anomaly_type: 'tax_disproportionate',
    severity: 'high',
    confidence: 'medium',
    title: 'Tax changed more than expected',
    description: 'What changed: Your tax went from £491.00 to £548.00 (11.6% change), while your gross pay only moved by 0.0%. That\'s a £57.00 difference in tax.\n\nWhy it matters: Tax usually moves roughly in line with gross pay. A disproportionate change often signals a tax code update, a one-off adjustment by HMRC, or a cumulative catch-up from a previous month.\n\nThis may be perfectly valid, but it\'s worth checking.',
    status: 'new',
    suggested_action: 'Compare the tax code shown on this payslip with last month\'s. If it\'s different, check your HMRC online account to confirm it\'s correct. If it\'s the same, ask payroll if a tax adjustment was applied.',
  },
  {
    id: 'an-003',
    payslip_id: 'ps-005',
    payslip_date: '2026-02-28',
    employer_name: 'Acme Technologies Ltd',
    anomaly_type: 'ni_disproportionate',
    severity: 'medium',
    confidence: 'medium',
    title: 'National Insurance changed more than expected',
    description: 'What changed: Your NI contributions went from £372.00 to £414.00 (11.3% change), while gross pay only moved by 0.0%. That\'s a £42.00 difference.\n\nWhy it matters: NI is calculated as a percentage of earnings above certain thresholds. A disproportionate change could indicate your NI category letter has changed, or that a salary sacrifice arrangement started or stopped.\n\nThis may be perfectly valid, but it\'s worth checking.',
    status: 'new',
    suggested_action: 'Check the NI category letter on your payslip (usually A, B, C, etc.). If it changed from last month, ask your payroll team why. You can also verify your NI record on the HMRC website.',
  },
  {
    id: 'an-004',
    payslip_id: 'ps-006',
    payslip_date: '2026-03-31',
    employer_name: 'Acme Technologies Ltd',
    anomaly_type: 'new_deduction',
    severity: 'medium',
    confidence: 'high',
    title: 'Student loan deduction appeared',
    description: 'What changed: A student loan repayment of £197.00 appeared this month but wasn\'t on your previous payslip.\n\nWhy it matters: HMRC may have notified your employer to begin deductions. This is normal if you\'re earning above the repayment threshold, but it\'s worth confirming the amount and plan type are correct.\n\nThis may be perfectly valid, but it\'s worth checking.',
    status: 'new',
    suggested_action: 'Log into your Student Loans Company account to check your repayment plan and threshold. Compare the deduction amount with what you\'d expect based on your plan type.',
  },
  {
    id: 'an-005',
    payslip_id: 'ps-006',
    payslip_date: '2026-03-31',
    employer_name: 'Acme Technologies Ltd',
    anomaly_type: 'net_pay_change',
    severity: 'high',
    confidence: 'high',
    title: 'Net pay dropped noticeably',
    description: 'What changed: Your take-home pay dropped from £2,695.00 to £2,540.00 — a £155.00 difference (5.8%).\n\nWhy it matters: A drop in net pay means less money reaching your account. This could be due to a tax code change, new deduction, or reduced hours.\n\nHere\'s what changed and why it may need review.',
    status: 'new',
    suggested_action: 'Compare this payslip\'s deductions line by line against last month. Look specifically at tax, National Insurance, and pension contributions to find what shifted.',
  },
];

export const demoIssueDrafts: IssueDraft[] = [
  {
    id: 'dr-001',
    payslip_id: 'ps-004',
    payslip_date: '2026-01-31',
    employer_name: 'Acme Technologies Ltd',
    subject: 'Query: Increased tax deduction on January payslip',
    body: `Dear Payroll Team,

I'm writing regarding my January 2026 payslip (dated 31 January 2026).

I noticed that my income tax deduction increased from £491 to £548, despite my gross pay remaining at £3,750. This represents an increase of approximately £57.

Could you please confirm:
1. Whether my tax code has changed, and if so, what it was updated to?
2. Whether this change was applied following a notification from HMRC?

I'd appreciate any clarification on this. Happy to discuss further if needed.

Kind regards`,
    status: 'draft',
    created_at: '2026-02-05T10:30:00Z',
  },
];

export const demoPayTrends: PayTrend[] = [
  { month: 'Oct', gross: 3750, net: 2737, tax: 491, deductions: 1013 },
  { month: 'Nov', gross: 3750, net: 2742, tax: 486, deductions: 1008 },
  { month: 'Dec', gross: 5250, net: 3612, tax: 891, deductions: 1638 },
  { month: 'Jan', gross: 3750, net: 2680, tax: 548, deductions: 1070 },
  { month: 'Feb', gross: 3750, net: 2695, tax: 491, deductions: 1055 },
  { month: 'Mar', gross: 3750, net: 2540, tax: 491, deductions: 1210 },
];

export const formatCurrency = (amount: number, country: 'UK' | 'Ireland' = 'UK') => {
  return country === 'Ireland'
    ? `€${amount.toLocaleString('en-IE', { minimumFractionDigits: 2 })}`
    : `£${amount.toLocaleString('en-GB', { minimumFractionDigits: 2 })}`;
};
