project_id = "shvivlhawhczbljzhvmr"

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.cancel-subscription-on-delete]
verify_jwt = false
